apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
  labels:
    app: github-actions-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
        - name: github-actions-runner
          image: 368085106192.dkr.ecr.us-east-1.amazonaws.com/runners:latest
          env:
            - name: VERSION
              value: "2.1.14"
            - name: GH_OWNER
              value: "sosotechnologies"
            - name: GH_REPOSITORY
              value: "runners"
            - name: GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token-secret
                  key: GH_TOKEN
      imagePullSecrets:
        - name: ecr-registry-secret