FROM ubuntu:24.04

ARG RUNNER_VERSION=2.317.0
ENV DEBIAN_FRONTEND=noninteractive

LABEL Author="cafanwi"
LABEL Email="sosotech2000@gmail.com"
LABEL GitHub="https://github.com/sosotechnologies"
LABEL BaseImage="ubuntu:20.04"
LABEL RunnerVersion=${RUNNER_VERSION}

# Update the base packages and add a non-sudo user
RUN apt-get update -y && apt-get upgrade -y && useradd -m docker

## install dependencies
RUN apt-get install -y --no-install-recommends \
    curl nodejs wget unzip vim git jq build-essential libssl-dev libffi-dev python3 python3-venv python3-dev python3-pip \
    git \
    wget \
    # xz-utils \
    # libavdevice-dev \
    # libavfilter-dev \
    # libswresample-dev \
    # cmake \
    # pkgconf \
    # build-essential \
    # libjpeg-dev \
    # libpng-dev \
    # libavcodec-dev \
    # libavformat-dev \
    # libavutil-dev \
    # libswscale-dev \
    # pkg-config \
    # #OpenSfM
    # python3-pyproj \
    # python3-dev \
    # python3-numpy \
    # python3-opencv \
    # python3-pip \
    # python3-scipy \
    # python3-yaml \
    # # openMVS
    # libboost-iostreams-dev \
    # libboost-system-dev \
    # libboost-serialization-dev \
    # libcgal-dev \
    # libeigen3-dev \
    # libopencv-dev \
    # libceres-dev \
    # unrar \
    # apache2 \
    # cron \
    # dateutils \
    # gnupg2 \
    # gdal-bin \
    # liblua5.3-dev \
    # lua5.3 \
    # mapnik-utils \
    # npm \
    # osm2pgsql \
    # osmium-tool \
    # osmosis \
    # python-is-python3 \
    # python3-mapnik \
    # python3-lxml \
    # python3-psycopg2 \
    # python3-shapely \
    # python3-pip \
    # renderd \
    # sudo \
    # vim \
    # gcc \
    # g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Download and setup GitHub Actions runner
RUN cd /home/docker && mkdir actions-runner && cd actions-runner && \
    curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz && \
    echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c && \
    tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz

# Install additional dependencies
RUN chown -R docker /home/docker && /home/docker/actions-runner/bin/installdependencies.sh

# Add and set up the start script
ADD runner-scripts/start.sh /home/docker/start.sh
RUN chmod +x /home/docker/start.sh

USER docker
ENTRYPOINT ["/home/docker/start.sh"]